#resolver: lts-11.0
resolver: nightly-2018-07-06
packages:
- '.'
#- location: ../bench-graph
#  extra-dep: true
allow-newer: true
extra-deps:
    - SDL-0.6.6.0

    - git: https://github.com/harendra-kumar/hs-gauge
      commit: 5ac72696cba8e1d747f98e1656a0cfac0a5e9c71

    - bench-graph-0.1.0
    - Chart-1.9
    - Chart-diagrams-1.9
    - Unique-0.4.7.2
    - SVGFonts-1.6.0.3

flags: {}
extra-package-dbs: []
rebuild-ghc-options: true
# For mac ports installed SDL library on Mac OS X
extra-include-dirs:
- /opt/local/include
