resolver: lts-12.11
packages:
- '.'
allow-newer: true
extra-deps:
    - SDL-0.6.6.0
    - gauge-0.2.3
    - Chart-1.9
    - Chart-diagrams-1.9
    - SVGFonts-1.6.0.3

    - git: https://github.com/composewell/bench-show
      commit: 38cb1b547d1a7ac62de09d59e28f4a1f71dba31b

flags: {}
extra-package-dbs: []
rebuild-ghc-options: true
# For mac ports installed SDL library on Mac OS X
extra-include-dirs:
- /opt/local/include
